name: Test Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup environment
      run: |
        sudo apt-get update
        sudo apt-get install autoconf automake libtool help2man make lcov gawk
    - name: automake
      run: ./scripts/bootstrap.sh
    - name: setup native compiler
      run: ./configure --enable-gcov
    - name: make
      run: make
    - name: make check
      run: make check
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      with:
        gcov: true
        fail_ci_if_error: true
        verbose: true
